"""v0.1.0 golden-corpus case definitions (F1 compatibility harness).

Single source of corpus INPUTS. Frozen EXPECTATIONS live in
``tests/data/v010_goldens.json`` and are generated by running these inputs
through the UNMODIFIED v0.1.0 kernel — never hand-written.

Regenerate (only deliberately, with owner-visible diff)::

    python3 tests/v010_cases.py --dump

Provenance is recorded in the JSON ``meta`` block (kernel version, git SHA,
command, ruleset label ``dutch-till2026-compat``).

Case kinds:
  engine    — pair_round(players, round, locked) must succeed; output pinned
              exactly (boards, colours, float tags, bye) + validator summary.
  validator — hand-built RoundResult checked with validate_round; rule-code
              summary pinned (codes + counts, not message text).
  error     — pair_round must raise; exception type + exact message pinned
              (message changes require deliberate golden review per O08).
"""

from __future__ import annotations

import sys

from pairing_core import PlayerData


def pd(pid, pno, rating, points=0.0, color_hist="", opponents=None,
       received_bye=False, float_hist=""):
    opp = frozenset(opponents) if opponents else frozenset()
    return PlayerData(id=pid, pairing_no=pno, rating=rating, points=points,
                      color_hist=color_hist, opponents=opp,
                      received_bye=received_bye, float_hist=float_hist)


def _flat(n, **kw):
    return [pd(i, i, 2000 - (i - 1) * 10, **kw) for i in range(1, n + 1)]


def _r1_decisive_8():
    """Round-2 state after a fully decisive 8-player round 1 (top half won)."""
    ps = []
    for i in (1, 2, 3, 4):
        ps.append(pd(i, i, 2000 - (i - 1) * 10, points=1.0,
                     color_hist="w", opponents={i + 4}))
    for i in (5, 6, 7, 8):
        ps.append(pd(i, i, 2000 - (i - 1) * 10, points=0.0,
                     color_hist="b", opponents={i - 4}))
    return ps


def _r2_draw_8():
    """Round-2 state: board 1 drew, other round-1 games decisive (top won)."""
    return [
        pd(1, 1, 1990, points=0.5, color_hist="w", opponents={5}),
        pd(2, 2, 1980, points=1.0, color_hist="w", opponents={6}),
        pd(3, 3, 1970, points=1.0, color_hist="w", opponents={7}),
        pd(4, 4, 1960, points=1.0, color_hist="w", opponents={8}),
        pd(5, 5, 1950, points=0.5, color_hist="b", opponents={1}),
        pd(6, 6, 1940, points=0.0, color_hist="b", opponents={2}),
        pd(7, 7, 1930, points=0.0, color_hist="b", opponents={3}),
        pd(8, 8, 1920, points=0.0, color_hist="b", opponents={4}),
    ]


def _r3_mixed_8():
    """Plausible round-3 state with colour + float histories in play."""
    return [
        pd(1, 1, 1990, points=2.0, color_hist="wb", opponents={5, 2},
           float_hist="-D"),
        pd(2, 2, 1980, points=2.0, color_hist="bw", opponents={6, 1}),
        pd(3, 3, 1970, points=1.5, color_hist="wb", opponents={7, 4},
           float_hist="D-"),
        pd(4, 4, 1960, points=1.5, color_hist="bw", opponents={8, 3}),
        pd(5, 5, 1950, points=1.0, color_hist="bw", opponents={1, 6},
           float_hist="U-"),
        pd(6, 6, 1940, points=1.0, color_hist="wb", opponents={2, 5}),
        pd(7, 7, 1930, points=0.5, color_hist="wb", opponents={3, 8}),
        pd(8, 8, 1920, points=0.5, color_hist="bw", opponents={4, 7},
           float_hist="-U"),
    ]


def build_cases():
    """Return the ordered list of corpus case dicts (inputs only)."""
    cases = []

    def add(cid, kind, desc, **kw):
        cases.append({"id": cid, "kind": kind, "desc": desc, **kw})

    # -- round-1 canonical shapes (even) ----------------------------------
    for n in (2, 4, 6, 8, 10, 12):
        add(f"E-r1-{n}", "engine", f"round 1, {n} players",
            players=_flat(n), round=1, locked=None)
    # -- round-1 odd fields (bye behaviour) --------------------------------
    for n in (3, 5, 7, 9):
        add(f"E-r1-odd-{n}", "engine", f"round 1, {n} players (bye)",
            players=_flat(n), round=1, locked=None)
    # -- edges -------------------------------------------------------------
    add("E-empty", "engine", "zero players", players=[], round=1, locked=None)
    add("E-single", "engine", "single player gets bye",
        players=_flat(1), round=1, locked=None)
    # -- mid-tournament states ----------------------------------------------
    add("E-r2-decisive", "engine", "round 2 after decisive round 1",
        players=_r1_decisive_8(), round=2, locked=None)
    add("E-r2-draw", "engine", "round 2 with 0.5 group (floats expected)",
        players=_r2_draw_8(), round=2, locked=None)
    add("E-r3-mixed", "engine", "round 3 mixed colours/floats",
        players=_r3_mixed_8(), round=3, locked=None)
    add("E-rematch", "engine", "rematch avoidance forces cross pairing",
        players=[pd(1, 1, 2000, points=1.0, opponents={2}),
                 pd(2, 2, 1900, points=1.0, opponents={1}),
                 pd(3, 3, 1800, points=1.0, opponents={4}),
                 pd(4, 4, 1700, points=1.0, opponents={3})],
        round=2, locked=None)
    add("E-abs-ww", "engine", "absolute colour: ww must take black",
        players=[pd(1, 1, 2000, color_hist="ww"),
                 pd(2, 2, 1900)], round=3, locked=None)
    add("E-abs-bb", "engine", "absolute colour: bb must take white",
        players=[pd(1, 1, 2000, color_hist="bb"),
                 pd(2, 2, 1900)], round=3, locked=None)
    add("E-strong", "engine", "strong preference wbw history recorded",
        players=[pd(1, 1, 2000, points=1.0, color_hist="wbw",
                     opponents={4}),
                 pd(2, 2, 1900, points=1.0, color_hist="bwb",
                     opponents={3}),
                 pd(3, 3, 1800, points=0.0, color_hist="wbw",
                     opponents={2}),
                 pd(4, 4, 1700, points=0.0, color_hist="bwb",
                     opponents={1})],
        round=4, locked=None)
    add("E-bye-mixed", "engine", "bye skips already-bye'd players",
        players=[pd(1, 1, 2000, received_bye=True),
                 pd(2, 2, 1900, received_bye=True),
                 pd(3, 3, 1800), pd(4, 4, 1700), pd(5, 5, 1600)],
        round=2, locked=None)
    add("E-locked", "engine", "locked pair placed verbatim",
        players=_flat(6), round=1, locked=[(1, 2)])
    # -- engine failure paths (error semantics are contract, O08) -----------
    add("X-impossible", "error", "fully-played field cannot pair",
        players=[pd(1, 1, 2000, opponents={2, 3, 4}),
                 pd(2, 2, 1900, opponents={1, 3, 4}),
                 pd(3, 3, 1800, opponents={1, 2, 4}),
                 pd(4, 4, 1700, opponents={1, 2, 3})],
        round=4, locked=None)
    add("X-lock-rematch", "error", "locked rematch rejected",
        players=[pd(1, 1, 2000, opponents={2}),
                 pd(2, 2, 1900, opponents={1})],
        round=2, locked=[(1, 2)])
    add("X-lock-unknown", "error", "locked unknown player rejected",
        players=_flat(4), round=1, locked=[(1, 99)])
    add("X-lock-self", "error", "locked self-pair rejected",
        players=_flat(4), round=1, locked=[(1, 1)])
    add("X-lock-dup", "error", "player in two locked pairs rejected",
        players=_flat(4), round=1, locked=[(1, 2), (1, 3)])
    add("X-lock-colour", "error", "colour-illegal lock rejected",
        players=[pd(1, 1, 2000, color_hist="ww"),
                 pd(2, 2, 1900, color_hist="ww")],
        round=3, locked=[(1, 2)])
    # -- validator behaviour on hand-built results --------------------------
    add("V-clean", "validator", "clean 4-player round validates",
        players=_flat(4), round=1,
        cards=[{"board": 1, "white": 1, "black": 3, "bye": False},
               {"board": 2, "white": 2, "black": 4, "bye": False}])
    add("V-rematch", "validator", "repeat opponents are ERROR GEN-01",
        players=[pd(1, 1, 2000, opponents={2}),
                 pd(2, 2, 1900, opponents={1})],
        round=2,
        cards=[{"board": 1, "white": 1, "black": 2, "bye": False}])
    add("V-triple-white", "validator", "ww player given white",
        players=[pd(1, 1, 2000, color_hist="ww"),
                 pd(2, 2, 1900)],
        round=3,
        cards=[{"board": 1, "white": 1, "black": 2, "bye": False}])
    add("V-two-byes", "validator", "two byes are ERROR GEN-02",
        players=_flat(4), round=1,
        cards=[{"board": 1, "white": 1, "black": None, "bye": True},
               {"board": 2, "white": 2, "black": None, "bye": True},
               {"board": 3, "white": 3, "black": 4, "bye": False}])
    add("V-repeat-bye", "validator", "repeat bye warns GEN-03",
        players=[pd(1, 1, 2000, received_bye=True),
                 pd(2, 2, 1900), pd(3, 3, 1800)],
        round=2,
        cards=[{"board": 1, "white": 2, "black": 3, "bye": False},
               {"board": 2, "white": 1, "black": None, "bye": True}])
    add("V-strong-pref", "validator", "missed strong preference warns",
        players=[pd(1, 1, 2000, color_hist="wbw"),
                 pd(2, 2, 1900)],
        round=4,
        cards=[{"board": 1, "white": 1, "black": 2, "bye": False}])
    add("V-mild-pref", "validator", "missed mild preference is INFO",
        players=[pd(1, 1, 2000, color_hist="bw"),
                 pd(2, 2, 1900)],
        round=3,
        cards=[{"board": 1, "white": 1, "black": 2, "bye": False}])
    add("V-boards", "validator", "non-sequential boards warn",
        players=_flat(4), round=1,
        cards=[{"board": 1, "white": 1, "black": 3, "bye": False},
               {"board": 3, "white": 2, "black": 4, "bye": False}])
    add("V-missing", "validator", "absent active player is ERROR COMP-01",
        players=_flat(4), round=1,
        cards=[{"board": 1, "white": 1, "black": 3, "bye": False}])
    add("V-unknown", "validator", "unknown paired id is ERROR COMP-02",
        players=_flat(2), round=1,
        cards=[{"board": 1, "white": 1, "black": 99, "bye": False}])
    add("V-dup", "validator", "player on two boards is ERROR GEN-DUP",
        players=_flat(4), round=1,
        cards=[{"board": 1, "white": 1, "black": 3, "bye": False},
               {"board": 2, "white": 1, "black": 4, "bye": False}])
    add("V-self", "validator", "self pairing is ERROR GEN-SELF",
        players=_flat(2), round=1,
        cards=[{"board": 1, "white": 1, "black": 1, "bye": False}])
    add("V-float-err", "validator", "third consecutive downfloat is ERROR",
        players=[pd(1, 1, 2000, points=1.0, float_hist="DD"),
                 pd(2, 2, 1900, points=0.0)],
        round=3,
        cards=[{"board": 1, "white": 2, "black": 1, "bye": False,
                "wfloat": "U", "bfloat": "D"}])
    return cases


def _player_to_json(p):
    return {"id": p.id, "pairing_no": p.pairing_no, "rating": p.rating,
            "points": p.points, "color_hist": p.color_hist,
            "opponents": sorted(p.opponents),
            "received_bye": p.received_bye, "float_hist": p.float_hist}


def dump(path="tests/data/v010_goldens.json"):
    """Run all cases through the kernel and freeze expectations to JSON."""
    import datetime
    import json
    import subprocess

    from pairing_core import PairingCard, RoundResult, pair_round, validate_round

    try:
        sha = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True,
                             text=True, check=True).stdout.strip()
    except Exception:
        sha = "UNKNOWN"

    out_cases = []
    for case in build_cases():
        kind = case["kind"]
        entry = {"id": case["id"], "kind": kind, "desc": case["desc"],
                 "round": case["round"],
                 "players": [_player_to_json(p) for p in case["players"]]}
        if kind == "engine":
            entry["locked"] = case["locked"]
            result = pair_round(case["players"], round_number=case["round"],
                                locked_pairs=case["locked"])
            rep = validate_round(result, case["players"])
            entry["expected"] = {
                "pairings": [
                    {"board": c.board, "white": c.white_id,
                     "black": c.black_id, "bye": c.is_bye,
                     "white_float": c.white_float,
                     "black_float": c.black_float}
                    for c in result.pairings],
                "bye_player_id": result.bye_player_id,
                "validation": _summary(rep),
            }
        elif kind == "validator":
            cards = [PairingCard(board=c["board"], white_id=c["white"],
                                 black_id=c.get("black"),
                                 is_bye=c.get("bye", False),
                                 white_float=c.get("wfloat", ""),
                                 black_float=c.get("bfloat", ""))
                     for c in case["cards"]]
            entry["cards"] = case["cards"]
            rep = validate_round(
                RoundResult(round_number=case["round"], pairings=cards),
                case["players"])
            entry["expected"] = {"validation": _summary(rep)}
        elif kind == "error":
            entry["locked"] = case["locked"]
            try:
                pair_round(case["players"], round_number=case["round"],
                           locked_pairs=case["locked"])
            except Exception as exc:  # noqa: BLE001 — golden must record it
                entry["expected"] = {"error": {
                    "type": type(exc).__name__, "message": str(exc)}}
            else:
                raise AssertionError(
                    f"golden error case {case['id']} did not raise")
        out_cases.append(entry)

    doc = {"meta": {
        "tool": "tests/v010_cases.py --dump (F1 harness)",
        "kernel": "pairing-core",
        "kernel_version": "0.1.0",
        "git_sha": sha,
        "ruleset_label": "dutch-till2026-compat",
        "date": datetime.date.today().isoformat(),
        "command": "python3 tests/v010_cases.py --dump",
        "note": ("Expectations recorded from the unmodified v0.1.0 kernel, "
                 "never hand-written. Regenerate only deliberately; review "
                 "every diff (O08)."),
    }, "cases": out_cases}

    with open(path, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, indent=2)
        fh.write("\n")
    print(f"wrote {len(out_cases)} cases to {path}")


def _summary(rep):
    return {"valid": rep.is_valid,
            "errors": sorted(f.rule for f in rep.errors),
            "warnings": sorted(f.rule for f in rep.warnings),
            "infos": sorted(f.rule for f in rep.findings
                            if f.level == "INFO")}


if __name__ == "__main__":
    if "--dump" in sys.argv:
        dump()
    else:
        print(f"{len(build_cases())} cases defined; use --dump to freeze")
